### ISSUE TITLE
runImpulseDE2 and SVA

### ISSUE THREAD

**Issue by gianfilippo** [YosefLab/ImpulseDE2#10]
Hi,

I just started trying out your algorithm. I already have the analysis done using edgeR and GLM, using SVA to correct for batch, etc . 
I introduced the SVA variables in the design matrix and referred to them by name using vecConfounders in runImpulseDE2
I get the error below for each of the SVA variables. What do you think ?

Thanks

ImpulseDE2 for count data, v1.6.1
# Process input
Error in checkData(dfAnnotation = dfAnnotation, matCountData = matCountData,  : 
  Model matrix based on confounding variables {SVA.1} is not full rank. Correct the confounding variables.  Note that it is not possible to model NESTED confounding variables:  Any confounding variables cannot be a linear combination of the other  confounding variables.

**Comment by davidsebfischer** [comment]
Hi @gianfilippo! Right now the code doesnt support continuous covariates unfortunately, the vector is turned into a categorical vector which then leads to an underdetermined error, ie non full-rank design matrix, which produces the error that you are seeing. I started writing a new backend that can deal with continuous covariates but it is not yet finished unfortunately. Even with the implementation working, one still has to take care with how / whether the components that you regress out are correlated with time, so doing this is not very trivial. Sorry about that!

**Comment by gianfilippo** [comment]
Hi,

thanks for the info. I look forward to the newer version of the algorithm. Nice work!

Best
