### ISSUE TITLE
Clustering_results

### ISSUE THREAD

**Issue by lcastro-bioinfo** [YosefLab/ImpulseDE2#2]
Hi there

I am conducting a study on cell differentiation with samples that come from RNAseq. ImpulseDE2 is very interesting for my project, and I'm starting to use it.
For me it is very important to perform clustering and to know in which cluster the genes have been classified. When using ImpulseDe, in the results could obtain this information (clustering_results). How can I get this clustering information in ImpulseDE2?

Thank you!!

**Comment by davidsebfischer** [comment]
Super sorry about the late reply, I will still leave it here in case somebody encounters the same issue: The model fitting procedure of ImpulseDE involved a gene trajectory clustering step. I think you are referring to these clusters. ImpulseDE2 uses an entirely different fitting algorithm which does not depend on such a clustering anymore. If you want to cluster, you would have to cluster the inferred trajectories separately. We offer the transient analysis as a variation of trajectory clustering that is based on interpretable models.
