### ISSUE TITLE
Unable to run successfully

### ISSUE THREAD

**Issue by mickmars51** [YosefLab/ImpulseDE2#33]
Hello Impulse Team, 

I am having an issue when adding my counts matrix and metadata the return is:

ImpulseDE2 for count data, v0.99.10
# Process input
Error in if (class(matCountData) == "SummarizedExperiment") { : 
  the condition has length > 1

I am also getting the error with the tutorial. How can I input a SummarizedExperiment instead of a count matrix? Hoping I can be steered in the right direction, thanks!

**Comment by svigneau** [comment]
I had the same problem and proposed a fix [here](https://github.com/YosefLab/ImpulseDE2/pull/34).

**Comment by davidsebfischer** [comment]
Merged into master now!
