### ISSUE TITLE
Wrong library size normalization ImpulseDE2_plotGenes.R

### ISSUE THREAD

**Issue by mplass** [YosefLab/ImpulseDE2#6]
Libray size normalization (lines 156-158) is wrong. 
Code:

```
 normCounts = get_matCountDataProc(
                    obj=objectImpulseDE2)[id,vecSamples]/
get_vecSizeFactors(objectImpulseDE2)[vecSamples], 
```

for Matrix division to work well  we have to transpose the first matrix
correct code

`normCounts = t(t(get_matCountDataProc(
                    obj=objectImpulseDE2)[id,vecSamples])/
get_vecSizeFactors(objectImpulseDE2)[vecSamples]), 
`
May this error be in other parts of the code? I get have of the genes DF (using sample only time course data)

**Comment by davidsebfischer** [comment]
Thanks for the issue! This issue refers to this code: https://github.com/YosefLab/ImpulseDE2/blob/12197fe75946b19293ac0addee34952e211721ef/R/srcImpulseDE2_plotGenes.R#L156. I think this is fine, this is within a loop an both objects are of the same length, I just put as.vector around each element of the fraction in a test script and this gives the same result. Note that this is not a matrix multiplication but an element-wise vector division. Please re-open if you have reason to believe that this is wrong!

`lsSimulatedData <- simulateDataSetImpulseDE2(
    vecTimePointsA   = rep(seq(1,8),3),
    vecTimePointsB   = NULL,
    vecBatchesA      = NULL,
    vecBatchesB      = NULL,
    scaNConst        = 0,
    scaNImp          = 40,
    scaNLin          = 20,
    scaNSig          = 40)
    objectImpulseDE2 <- runImpulseDE2(
    matCountData    = lsSimulatedData$matObservedCounts, 
    dfAnnotation    = lsSimulatedData$dfAnnotation,
    boolCaseCtrl    = FALSE,
    vecConfounders  = NULL,
    boolIdentifyTransients = FALSE,
    scaNProc        = 1 )
lsgplotsID <- plotGenes(
    scaNTopIDs=5,
    objectImpulseDE2=objectImpulseDE2,
    boolCaseCtrl=FALSE,
    boolMultiplePlotsPerPage=TRUE,
    boolSimplePlot=FALSE)
print(get_matCountDataProc(obj=objectImpulseDE2)[1,]/get_vecSizeFactors(objectImpulseDE2))
print(as.vector(get_matCountDataProc(obj=objectImpulseDE2)[1,])/as.vector(get_vecSizeFactors(objectImpulseDE2)))
plot(get_matCountDataProc(obj=objectImpulseDE2)[1,]/get_vecSizeFactors(objectImpulseDE2), get_matCountDataProc(obj=objectImpulseDE2)[1,])`
