### ISSUE TITLE
TimeCateg error

### ISSUE THREAD

**Issue by jchariker** [YosefLab/ImpulseDE2#8]
Hi,

When running the following command:
objectImpulseDE2 <- runImpulseDE2(
  matCountData    = mat, 
  dfAnnotation    = sampleTable,
  boolCaseCtrl = TRUE,
  scaQThres = pVal,
  boolIdentifyTransients = TRUE)

I get this error:
ImpulseDE2 for count data, v1.8.0
# Process input
Error in `$<-.data.frame`(`*tmp*`, "TimeCateg", value = "_") : 
  replacement has 1 row, data has 0
Timing stopped at: 0.03 0 0.04

My dfAnnotation file consists of this:
     Sample                               Condition Time
1   MH-01-S21-RT-naive-IN_S1   control    1
2   MH-02-S21-RT-naive-IP_S2      case    1
3   MH-03-S22-RT-naive-IN_S3   control    1
4   MH-04-S22-RT-naive-IP_S4      case    1
5   MH-05-S23-RT-naive-IN_S5   control    1
6   MH-06-S23-RT-naive-IP_S6      case    1
7    MH-07-S12-RT-2DPI-IN_S7   control    2
8    MH-08-S12-RT-2DPI-IP_S8      case    2
9    MH-09-S13-RT-2DPI-IN_S9   control    2
10  MH-10-S13-RT-2DPI-IP_S10      case    2
11  MH-11-S14-RT-2DPI-IN_S11   control    2
12  MH-12-S14-RT-2DPI-IP_S12      case    2
13 MH-13-S15-RT-10DPI-IN_S13   control    3
14 MH-14-S15-RT-10DPI-IP_S14      case    3
15 MH-15-S16-RT-10DPI-IN_S15   control    3
16 MH-16-S16-RT-10DPI-IP_S16      case    3
17 MH-17-S17-RT-10DPI-IN_S17   control    3
18 MH-18-S17-RT-10DPI-IP_S18      case    3
19 MH-19-S18-RT-42DPI-IN_S19   control    4
20 MH-20-S18-RT-42DPI-IP_S20      case    4
21 MH-21-S19-RT-42DPI-IN_S21   control    4
22 MH-22-S19-RT-42DPI-IP_S22      case    4
23 MH-23-S20-RT-42DPI-IN_S23   control    4
24 MH-24-S20-RT-42DPI-IP_S24      case    4

My count matrix has 24 columns of data. 

Do you have any idea what the problem might be? 
Thanks for your help!
Julia

**Comment by davidsebfischer** [comment]
Hi @jchariker! Thanks for the issue! 
1. Is that the full error trace? 
2. Can you just check that the entries in the `Time` columns are numeric?

**Comment by jchariker** [comment]
Yes, that is the full error trace. I realized early on that the Time column needed to be numeric, and I set the following. 
sampleTable$Time<-as.numeric(sampleTable$Time)

The result of checking that is:
> typeof(sampleTable$Time)
[1] "double"

In trying to figure out what was going on with TimeCateg, I noticed the following in srcImpulseDE2_processData.R:

# Add categorial time column for DESeq2
dfAnnotationProc$TimeCateg <- paste0("_", dfAnnotationProc$Time)

Perhaps to paste, Time needs to be a string?  ...or I'm way off base!
Thanks for responding so quickly!
Julia

**Comment by davidsebfischer** [comment]
Can you please post this here:
```
colnames(matCounts)  # the count matrix that you input
```
I could reproduce a similar behaviour if the count matrix columns (samples) did not have the same names as the samples in the dfAnnotation. Please also set the rownames of dfAnnotation to the sample names:
```
rownames(dfAnnotation) <- dfAnnotation$Sample
```
Assuming that the columns of the count matrix are sorted accordingly, you can
```
colnames(matCounts) <- dfAnnotation$Sample
```
to enure consistent naming.

**Comment by jchariker** [comment]
Inconsistent naming was the problem. My count matrix had hyphens in the column names, which R substituted with dots on reading in the file. For example, the header MH-01-S21-RT-naive-IN_S1 was changed to MH.01.S21.RT.naive.IN_S1. Once the column names in the count matrix were in agreement with dfAnnotation$Sample, the code ran beautifully. 

Thank you for finding the answer so quickly! I really appreciate it, and I am looking forward to exploring the results! 
Julia

**Comment by davidsebfischer** [comment]
Happy to hear that Julia! Let me know if you encounter other issues!
